// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGKTlKnokBPNIiFmKHoWRsWapvpMNogjo',
    appId: '1:630132349312:web:c1ae94155f3e6c24460965',
    messagingSenderId: '630132349312',
    projectId: 'padmavati-893e5',
    authDomain: 'padmavati-893e5.firebaseapp.com',
    storageBucket: 'padmavati-893e5.appspot.com',
    measurementId: 'G-51NFFPQ2RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqCNkzU4JMkjWxDpMjnQTB69xM5ej_b4',
    appId: '1:630132349312:android:9ccfe9e0643eda5d460965',
    messagingSenderId: '630132349312',
    projectId: 'padmavati-893e5',
    storageBucket: 'padmavati-893e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtgFNIottNShj-pxNarKWJiBvzBv2LzAQ',
    appId: '1:630132349312:ios:7d369fab2b606a6a460965',
    messagingSenderId: '630132349312',
    projectId: 'padmavati-893e5',
    storageBucket: 'padmavati-893e5.appspot.com',
    iosBundleId: 'com.example.padmavatiAssignment',
  );
}
